stages:
  - build
  - lint_format
  - migrations
  - test
  - deploy


Lint:
  stage: lint_format
  script:
    - docker run --rm --network mainNetwork cars_rent_api ruff check


Format:
  stage: lint_format
  script:
    - docker run --rm --network mainNetwork cars_rent_api ruff format --check


Migrations:
  stage: lint_format
  script:
    - docker run --rm --network mainNetwork cars_rent_api alembic upgrade head


Tests:
  stage: test
  script:
    - docker run --rm --network mainNetwork cars_rent_api pytest -s -v


build-job:
  stage: build
  before_script:
    - echo "${ENV}" > .env
    - echo "${TEST_ENV}" > .env-test
  script:
    - docker build -t cars_rent_api .


deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d
    - docker exec cars_rent_nginx nginx -s reload