stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - echo "${ENV}" > .env
    - echo "${TEST_ENV}" > .env-test
  script:
    - docker build -t cars_rent_api .

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d
    - docker exec cars_rent_nginx nginx -s reload