services:
  cars_rent_back_service:
    container_name: 'cars_rent_back'
    build:
      context: .
    networks:
      - mainNetwork
    env_file:
      - .env

  cars_rent_celery_worker_service:
    container_name: 'cars_rent_celery_worker'
    build:
      context: .
    networks:
      - mainNetwork
    env_file:
      - .env
    command: "celery --app=app.tasks.celery_app:celery_instance worker -l INFO"

  cars_rent_celery_beat_service:
    container_name: 'cars_rent_celery_beat'
    build:
      context: .
    networks:
      - mainNetwork
    env_file:
      - .env
    command: "celery --app=app.tasks.celery_app:celery_instance beat -l INFO"

networks:
  mainNetwork:
    external: True